
services:
  webapp:
    image: ${WEBAPP_IMAGE}
    ports:
      - "3000:8080"
    env_file:
      - .env
    restart: always
  api:
    image: ${API_IMAGE}
    ports:
      - "5000:5050"
    env_file:
      - .env
    restart: always